apiVersion: v1 
kind: Pod
metadata:
  name: annotation-demo 
  namespace: sidhu-namespaces
  annotations: 
   project: annotation-k8s
   module: FE
   environment: dev
spec:
  containers:
   - name: nginx-con1
     image: nginx
