apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: static-volume
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1c
      containers:
      - name: app-nginx
        image: nginx
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim



---

apiVersion: v1
kind: Service
metadata:
  name: sidhu-nodeport
  namespace: static-volume
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: nginx-service-nodeport
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30015
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: static-volume
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: test-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: static-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c73851f207ee4b52