apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: robo
data:
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: robo
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc= 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: robo
  labels:
    name: mysql
    project: robo
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels: # should match with pod
      name: mysql
      project: robo
      tier: db
  template: # pod defination
    metadata:
      labels: # pod labels
        name: mysql
        project: robo
        tier: db
    spec:
      containers:
      - name: mysql
        image: iamroyalreddy/mysql:v1
        resources:
         requests:
          memory: "64Mi"
          cpu: "250m"
         limits:
          memory: "128Mi"
          cpu: "500m"
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: mysql
          - configMapRef:
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: robo
spec:
  selector:
    name: mysql
    project: robo
    tier: db 
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #container-port