apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: robo
  labels:
    name: mongodb
    project: robo
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels: # should match with pod
      name: mongodb
      project: robo
      tier: db
  template: # pod defination
    metadata:
      labels: # pod labels
        name: mongodb
        project: robo
        tier: db
    spec:
      containers:
      - name: mongodb
        image: iamroyalreddy/mongodb:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: robo
spec:
  selector:
    name: mongodb
    project: robo
    tier: db 
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017 #container-port