apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dynamic-volume
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app-nginx
        image: nginx
        volumeMounts:
        - name: dynamic-storage
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: dynamic-storage
        persistentVolumeClaim:
          claimName: ebs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sidhu-nodeport
  namespace: dynamic-volume
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: nginx-service-nodeport
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30015
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-dynamic
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: dynamic-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-dynamic
  resources:
    requests:
      storage: 4Gi
