apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dynamic-volume
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app-nginx
        image: nginx
        volumeMounts:
        - name: dynamic-storage
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: dynamic-storage
        persistentVolumeClaim:
          claimName: ebs-claim