apiVersion: v1 
kind: Pod
metadata:
  name: nginx-pod
  namespace: sidhu-namespaces
spec:
  containers:
   - name: nginx-con
     image: nginx
     env:
     - name: course
       valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: course
     - name: duration
       valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: duration
