apiVersion: v1 
kind: Pod
metadata:
  name: nginx-pod
  namespace: sidhu-namespaces
spec:
  containers:
   - name: nginx-con-10
     image: nginx
     envFrom:
        - configMapRef:
            name: nginx-config
