apiVersion: v1
kind: Pod
metadata:
  name: cluster-ip-svc
  namespace: sidhu-namespaces
  labels: 
    project: service-sidhu
    module: be
    environment: dev
spec:
  containers:
  - name: app-nginx-cip
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: sidhu-namespaces
spec:
  type: ClusterIP
  selector:
    project: service-sidhu
    module: be
    environment: dev
  ports:
  - name: nginx-service-cip-port
    protocol: TCP
    port: 80
    targetPort: 80
