apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: sidhu-project-01
  labels:
    app: DB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DB
  template:
    metadata:
      labels:
        app: DB
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: sidhu-project-01
spec:
  selector:
   app: DB
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306

