apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: robo
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: robo
  labels:
    name: cart
    project: robo
    tier: app 
spec:
  replicas: 1
  selector:
    matchLabels: # deployment-set labels
      name: cart
      project: robo
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: cart
        project: robo
        tier: app
    spec:
      containers:
      - name: cart
        image: iamroyalreddy/cart:v1
        resources:
         requests:
          memory: "64Mi"
          cpu: "250m"
         limits:
           memory: "128Mi"
           cpu: "500m"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: robo
spec:
  selector:
    name: cart
    project: robo
    tier: app 
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port