apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e124d21f2d6a2f93

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app-nginx
        image: nginx
        volumeMounts:
        - name: expense-efs
          mountPath: /usr/share/nginx/html
        ports:                           # Correct placement of ports
        - containerPort: 80
      volumes:
      - name: expense-efs
        persistentVolumeClaim:
          claimName: efs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sidhu-nodeport
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: nginx-service-nodeport
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30005
